/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        accent: '#E85D3A',
        'accent-light': '#F06B4A',
        'accent-muted': '#D64F28',
        'bg-base': '#F8F9FA',
        surface: '#FFFFFF',
        'surface-container': '#F3F4F6',
        'surface-high': '#E8EAED',
        'text-primary': '#1A1A2E',
        'text-secondary': '#4A4A5A',
        'text-tertiary': '#8E8E9A',
        positive: '#10B981',
        'positive-light': '#D1FAE5',
        negative: '#EF4444',
        'negative-light': '#FEE2E2',
        info: '#3B82F6',
        warning: '#F59E0B',
        border: '#E5E7EB',
        'border-subtle': '#F0F2F5',
        sidebar: '#1A1A2E',
        'sidebar-hover': '#252540',
        'sidebar-active': '#E85D3A',
        // Category colors
        'cat-dining': '#E07A6E',
        'cat-grocery': '#6ABB8A',
        'cat-shopping': '#BD82D6',
        'cat-superstore': '#6BA3D6',
        'cat-transit': '#D4A853',
        'cat-gas': '#A68E7A',
        'cat-rent': '#B07D62',
        'cat-utilities': '#7A9BAE',
        'cat-transfer': '#8DB580',
        'cat-fee': '#8A8C94',
        'cat-loan': '#B88A6E',
        'cat-entertainment': '#D680B0',
        'cat-travel': '#5CBAA3',
        'cat-subscription': '#8A8DE0',
        'cat-medical': '#E09878',
        'cat-personal-care': '#D8A8C4',
        'cat-professional': '#9CA8B8',
        'cat-education': '#88B5D6',
        'cat-uncategorized': '#9B9B9B',
      },
      fontFamily: {
        sora: ['Sora_400Regular'],
        'sora-medium': ['Sora_500Medium'],
        'sora-semibold': ['Sora_600SemiBold'],
        'sora-bold': ['Sora_700Bold'],
      },
      borderRadius: {
        card: '16px',
        btn: '12px',
      },
    },
  },
  plugins: [],
};
